house_prices:
  train_dataset: ../../datasets/house_prices/train.csv
  test_dataset: ../../datasets/house_prices/test.csv
house_prices_hw:
  train_dataset: ../../datasets/house_prices_hw/train.csv
  test_dataset: ../../datasets/house_prices_hw/test.csv
fake_news:
  train_dataset: ../../datasets/fake_news/train.csv
  test_dataset: ../../datasets/fake_news/test.csv
