house_pricing:
  train_dataset: ../house_prices/train.csv
  test_dataset: ../house_prices/test.csv
classification:
  wdbc: ../classification/data.csv
  mushrooms: ../classification/mushrooms.csv
clustering:
  flowcytometry: ../flow_cytometry
